services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scrypt-network
  keycloak:
    image: keycloak/keycloak:26.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_LOG_LEVEL: info
      KC_HTTP_ENABLED: true
      KC_METRICS_ENABLED: false
      KC_HEALTH_ENABLED: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command: start-dev
    volumes:
      - ./build/libs/keycloak-firebase-scrypt-latest.jar:/opt/keycloak/providers/keycloak-firebase-scrypt-latest.jar
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 9000:9000
    networks:
      - scrypt-network

volumes:
  pgdata:
    driver: local

networks:
  scrypt-network:
    driver: bridge
